package com.fivucsas.identity.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.springframework.data.domain.Persistable;

import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "refresh_tokens")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RefreshToken implements Persistable<UUID> {

    @Id
    private UUID id;

    /**
     * Spring Data isNew() override (P0-PROD bug 2026-05-04 fix).
     *
     * <p>P1-1 (PR #56, 2026-05-02) introduced the wire format
     * {@code <id>.<secret>} which forces us to know the row id before save so
     * we can build the wire token. The previous code did
     * {@code .id(UUID.randomUUID())} on the builder which, combined with
     * {@code @GeneratedValue}, fooled Spring Data's default {@code isNew()}
     * (id-is-null check) into seeing every fresh row as already-persistent.
     * {@code SimpleJpaRepository.save} therefore went through {@code merge}
     * instead of {@code persist}, hit the detached-merge path, and threw
     * {@code StaleObjectStateException} on every mint between 2026-05-02
     * (rebuild) and 2026-05-04 — every MFA step that completed a flow could
     * not produce its refresh token.
     *
     * <p>Implementing {@link Persistable} with an explicit transient
     * {@code newEntity} flag lets us pre-assign the id deterministically and
     * still tell Spring Data this is a brand-new row, so {@code save} routes
     * to {@code persist} (INSERT). After {@code @PostLoad} or
     * {@code @PostPersist}, {@code newEntity} flips to {@code false} so a
     * subsequent in-place update goes through {@code merge} as normal.</p>
     */
    @Transient
    @Builder.Default
    private boolean newEntity = true;

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return newEntity;
    }

    @PostLoad
    @PostPersist
    void markPersistent() {
        this.newEntity = false;
    }

    /**
     * JPA-safe equality by immutable id (P2.10). Replaces the Lombok {@code @Data}
     * default which included {@code user} (a lazy {@code @ManyToOne}) — that would
     * trigger proxy initialization on every {@code equals}/{@code hashCode} and
     * could StackOverflow via the back-reference. See {@link User#equals(Object)}
     * for the full rationale.
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RefreshToken other)) return false;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return RefreshToken.class.hashCode();
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * One-time, at-mint visibility of the full wire token {@code <id>.<secret>}.
     *
     * <p>This is the only place the secret-half exists outside of the
     * authorization-server response: it is set inside
     * {@link com.fivucsas.identity.service.RefreshTokenService#createRefreshTokenInFamily}
     * before save, returned to the caller through the same entity, and is
     * never re-hydrated from the database (loading a row from JPA leaves
     * this field {@code null}). After the calling service has written the
     * wire token into the HTTP response body it is unreachable for the
     * lifetime of the row.
     *
     * <p>{@code @Transient} so JPA does not try to map this to a column —
     * the plaintext column itself was dropped by V60 (2026-05-11). The
     * field name + accessor stayed {@code token / getToken} so the four
     * call sites that thread the response body
     * ({@code AuthenticationResponse.of(accessToken, refreshToken.getToken(), …)})
     * keep working without churn.</p>
     *
     * <p>Setter ({@code setToken}) is generated by Lombok and used by
     * {@code RefreshTokenService} at mint time only.</p>
     */
    @Transient
    private String token;

    /**
     * SHA-256 of the refresh-token secret-half (P1-1, 2026-05-02).
     *
     * <p>The wire token has the form {@code <id>.<secret>}; only the digest
     * of the secret-half is persisted. The plaintext {@code token} column
     * was dropped by V60 (2026-05-11) after the 7-day soak window closed —
     * see {@code RefreshTokenService.findByToken} for the resolution path.</p>
     *
     * <p>See {@link com.fivucsas.identity.service.RefreshTokenHasher} and
     * {@code SECURITY_REVIEW_2026-05-01.md} §P1-1.
     */
    @Column(name = "token_secret_hash", nullable = false)
    private byte[] tokenSecretHash;

    /**
     * Rotation-family identifier (Sec-P2 #6, 2026-04-29).
     *
     * <p>All refresh tokens minted from a single initial login share one
     * family_id, propagated through every rotation. When the application
     * detects replay of a revoked token, every row sharing this family_id
     * is revoked at once — RFC 6749 §10.4 + OAuth 2.0 Security BCP §4.13.
     * See {@code RefreshTokenService.rotateRefreshToken}.
     */
    @Column(name = "family_id", nullable = false)
    private UUID familyId;

    /**
     * OAuth2 client this token was issued to (API-2, 2026-06-06, V84).
     *
     * <p>The wire {@code client_id} string (matches {@code oauth2_clients.client_id})
     * of the relying party that minted this token through the OAuth2
     * {@code authorization_code} exchange. {@code NULL} = legacy / client-unbound —
     * minted by a non-OAuth path ({@code /auth/login}, register, MFA-step,
     * membership-switch, usernameless) which is not tied to a single RP, OR minted
     * before V84. On the {@code refresh_token} grant a non-null value must equal the
     * requesting client (else {@code invalid_grant}) so a refresh token issued to
     * app A is not replayable by app B; a {@code NULL} value is accepted (grace
     * window). The rotated successor inherits this binding via
     * {@code RefreshTokenService.rotateRefreshToken}. Nullable column, no backfill.</p>
     */
    @Column(name = "client_id", length = 128)
    private String clientId;

    @Column(nullable = false)
    private Instant expiryDate;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    @Column
    private Instant revokedAt;

    @Column(name = "is_revoked")
    @Builder.Default
    private boolean isRevoked = false;

    @Column(length = 45)
    private String ipAddress;

    @Column(length = 500)
    private String userAgent;

    public boolean isExpired() {
        return Instant.now().isAfter(this.expiryDate);
    }

    public void revoke() {
        this.isRevoked = true;
        this.revokedAt = Instant.now();
    }
}
